`parse_dns_name` bug fix (#397)
Before this parsing fix, mdns parsing failed because a space was escaped
when using Name::to_String() from the domain crate. The
Label::fmt::Display in the domain crate seems to explicitly escape ` `,
`.`, and `\\`
https://github.com/NLnetLabs/domain/blob/main/src/base/name/label.rs#L439.

so, i made a change to use the iterator, get each label, get its bytes
and convert to str. (also have to filter out the root empty label to
avoid a trailing dot.

```
failures:

---- transport::network::mdns::resolve::tests::parse_dns_name_service_instance stdout ----

thread 'transport::network::mdns::resolve::tests::parse_dns_name_service_instance' (164797) panicked at rs-matter/src/transport/network/mdns/resolve.rs:421:9:
assertion `left == right` failed
  left: Some("Matter\\ Device._matterc._udp.local")
 right: Some("Matter Device._matterc._udp.local")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```