Use "switch" instead of "checkout" for checking out CHIP repo (#369)
When running the integration tests I ran in to the following error.

```bash
cargo xtask itest
> Setting up Chip environment...
  > System tools check passed
  > Cloning Chip repository...
  > Checking out Chip GIT reference: v1.4.2-branch...
fatal: 'v1.4.2-branch' could be both a local file and a tracking branch.
Please use -- (and optionally --no-guess) to disambiguate
Error: Command failed with status: exit status: 128
```

This PR updates the git command from `checkout` to `switch` to remove
the ambiguity.